# Generated by Django 4.2.6 on 2024-05-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_model_1_delete_моямодель'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_1',
        ),
    ]
