# Generated by Django 4.2.6 on 2024-05-08 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0003_delete_model_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id_discipline', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('number_1_sem_grade', models.IntegerField(db_column='1_sem_grade')),
                ('number_2_sem_grade', models.IntegerField(db_column='2_sem_grade')),
                ('final_grade', models.IntegerField()),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id_principal', models.AutoField(primary_key=True, serialize=False)),
                ('full_name_principal', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'principal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalInfo',
            fields=[
                ('id_principal_info', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('adress', models.CharField(max_length=45)),
                ('phone_field', models.IntegerField(db_column='phone_╣')),
                ('birth_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'principal_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('full_name_student', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('full_name_teacher', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id_student', models.OneToOneField(db_column='id_student', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school.student')),
                ('email', models.CharField(max_length=45)),
                ('phone_field', models.CharField(db_column='phone_╣', max_length=18)),
                ('birth_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id_teacher', models.OneToOneField(db_column='id_teacher', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school.teacher')),
                ('email', models.CharField(max_length=45)),
                ('phone_field', models.CharField(db_column='phone_╣', max_length=15)),
                ('birth_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'teacher_info',
                'managed': False,
            },
        ),
    ]
