# Generated by Django 4.2.6 on 2024-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
    ]
