# Generated by Django 4.2.6 on 2024-05-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={},
        ),
    ]
