# Generated by Django 4.2.6 on 2024-05-11 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0006_alter_principal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='id_principal_info',
            field=models.ForeignKey(db_column='id_principal_info', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='school.principalinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principal',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='principal',
            name='id_principal',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
