# Generated by Django 4.2.6 on 2024-05-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_principal_id_principal_info_principal_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='id_principal_info',
            field=models.ForeignKey(db_column='id_principal_info', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.principalinfo'),
        ),
    ]
