# Generated by Django 4.2.6 on 2024-05-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_principal_id_principal_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'managed': False},
        ),
    ]
